### ISSUE TITLE
flatpak対応

### ISSUE THREAD

**Issue by aruelu** [aruelu/appinstall#3]
flatpakでのソフトウェアのインストールに対応する。

**Comment by rkarsnk** [comment]
@aruelu flatpak_fc-cache.shの処理内容は，appinstall_flatpak.sh内で`flatpak install $APPID`の後に実行するのでは何か問題があるかな?

**Comment by aruelu** [comment]
> @aruelu flatpak_fc-cache.shの処理内容は，appinstall_flatpak.sh内で`flatpak install $APPID`の後に実行するのでは何か問題があるかな?

全てのソフトで実行しても問題無さそうなので変更します。
