### ISSUE TITLE
ファイル名の変更

### ISSUE THREAD

**Issue by rkarsnk** [aruelu/appinstall#4]
flatpak対応にともない，以下のようにファイル名を変更してもいいかも．
- run_appinstall.sh -> appinstall
- appinstall.sh -> apt_install.sh
- appinstall.conf -> apt.conf
- appinstall_flatpak.sh -> flatpak_install.sh
- appinstall_flatpak.conf -> flatpak.conf

あと，appinstallとsetup.shには`chmod +x`しておいた方がいいかも．

**Comment by aruelu** [comment]
有り難うございます。
分かりやすくなるので、変更してみます。

**Comment by aruelu** [comment]
ファイル名変更対応済
